spring.application.name=springeccom
spring.datasource.url = jdbc:postgresql://ep-divine-cherry-ambrxdhe-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username = neondb_owner
spring.datasource.password = npg_XIunGO9rF4DA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
