spring.application.name=spring-oauth
# This is for github code space to forward the port
server.forward-headers-strategy=framework

spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=